"""empty message

Revision ID: 6d51d28fb8d7
Revises: a91d8645f5c6
Create Date: 2020-12-02 09:29:38.624693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d51d28fb8d7'
down_revision = 'a91d8645f5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
