"""empty message

Revision ID: a17aa6add539
Revises: 6d51d28fb8d7
Create Date: 2020-12-02 10:28:23.888077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17aa6add539'
down_revision = '6d51d28fb8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'user_id')
    # ### end Alembic commands ###
