"""empty message

Revision ID: a3480ffc17b1
Revises: a17aa6add539
Create Date: 2020-12-12 01:46:23.892679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3480ffc17b1'
down_revision = 'a17aa6add539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=True),
    sa.Column('firstname', sa.String(length=16), nullable=True),
    sa.Column('lastname', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=16), nullable=True),
    sa.Column('password', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('userrole', sa.String(length=16), nullable=True),
    sa.Column('untipassword', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_lastname'), 'user', ['lastname'], unique=False)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_index(op.f('ix_user_untipassword'), 'user', ['untipassword'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_index(op.f('ix_user_userrole'), 'user', ['userrole'], unique=False)
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Integer(), nullable=True),
    sa.Column('create_data', sa.DATETIME(), nullable=True),
    sa.Column('last_edit_data', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('new_text', sa.String(length=16), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('datetimeofrequest', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('request_id', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_new_text'), 'request', ['new_text'], unique=False)
    op.create_index(op.f('ix_request_request_id'), 'request', ['request_id'], unique=False)
    op.create_index(op.f('ix_request_status'), 'request', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_status'), table_name='request')
    op.drop_index(op.f('ix_request_request_id'), table_name='request')
    op.drop_index(op.f('ix_request_new_text'), table_name='request')
    op.drop_table('request')
    op.drop_table('article')
    op.drop_index(op.f('ix_user_userrole'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_untipassword'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_lastname'), table_name='user')
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
