"""empty message

Revision ID: a91d8645f5c6
Revises: 0bcf0bc89f7b
Create Date: 2020-12-02 01:48:26.155989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91d8645f5c6'
down_revision = '0bcf0bc89f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
