"""empty message

Revision ID: d2b4677867e9
Revises: caae4a63c34d
Create Date: 2020-12-02 01:43:36.533123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b4677867e9'
down_revision = 'caae4a63c34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_request_Status'), 'request', ['Status'], unique=False)
    op.create_index(op.f('ix_request_new_text'), 'request', ['new_text'], unique=False)
    op.create_index(op.f('ix_request_request_id'), 'request', ['request_id'], unique=False)
    op.drop_index('ix_Request_Status', table_name='request')
    op.drop_index('ix_Request_new_text', table_name='request')
    op.drop_index('ix_Request_request_id', table_name='request')
    op.add_column('user', sa.Column('untipassword', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_firstName'), 'user', ['firstName'], unique=False)
    op.create_index(op.f('ix_user_lastName'), 'user', ['lastName'], unique=False)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_index(op.f('ix_user_untipassword'), 'user', ['untipassword'], unique=False)
    op.create_index(op.f('ix_user_userRole'), 'user', ['userRole'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.drop_index('ix_User_email', table_name='user')
    op.drop_index('ix_User_firstName', table_name='user')
    op.drop_index('ix_User_lastName', table_name='user')
    op.drop_index('ix_User_password', table_name='user')
    op.drop_index('ix_User_phone', table_name='user')
    op.drop_index('ix_User_userRole', table_name='user')
    op.drop_index('ix_User_username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_User_username', 'user', ['username'], unique=False)
    op.create_index('ix_User_userRole', 'user', ['userRole'], unique=False)
    op.create_index('ix_User_phone', 'user', ['phone'], unique=False)
    op.create_index('ix_User_password', 'user', ['password'], unique=False)
    op.create_index('ix_User_lastName', 'user', ['lastName'], unique=False)
    op.create_index('ix_User_firstName', 'user', ['firstName'], unique=False)
    op.create_index('ix_User_email', 'user', ['email'], unique=False)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_userRole'), table_name='user')
    op.drop_index(op.f('ix_user_untipassword'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_lastName'), table_name='user')
    op.drop_index(op.f('ix_user_firstName'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'untipassword')
    op.create_index('ix_Request_request_id', 'request', ['request_id'], unique=False)
    op.create_index('ix_Request_new_text', 'request', ['new_text'], unique=False)
    op.create_index('ix_Request_Status', 'request', ['Status'], unique=False)
    op.drop_index(op.f('ix_request_request_id'), table_name='request')
    op.drop_index(op.f('ix_request_new_text'), table_name='request')
    op.drop_index(op.f('ix_request_Status'), table_name='request')
    # ### end Alembic commands ###
